GS_SHEET_ID = "1BTkOmjj-nMxKgPxCNFeRe2OTjch0pE9shPzTGjGFntI"

[gcp_service_account]
type = "service_account"
project_id = "braided-complex-481413-h8"
private_key_id = "d698b5f4703154d93aee0211188f9b2201982424"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC9n9iaIHmEaGWG
CIVUadBnCb1Q8cM9reEnBu0eDAFVAZuP8WHzbcUmdtl+tOFg+2f/YjXiuoKuYW5j
4wA12KIKk90O/hqDHPNe53R+glhR3EskfGpnEEEXwKBdq8iU3+FxjjgJoetXG7r7
fuersKDuOrxtzVPnhaSfJW0ZF2AhTlWuRpUHv08a/5HT8E4DAASKcpiEtH8R9GK6
nz3Q2sVSljupZy1MD6vdRqvMFt0kwAdACv1goS//pVgcD+nRTxZb2bkiXD1aR+Bl
0r32n0rOPkoOsaiXuPuZGu/DhVQC5LENBd7aC0iw7B7GDWkakZNq6qU2SXdvbqxs
6bNd8RzjAgMBAAECggEATfE4HRIgILawlElIVIwx50hvkqftMpsYIuyL5n/UxFYm
1SHIu0Bxev/7IkPDKBPuiWCa+ZjkQj02HMSfv4JOCL8CbDkyOJZbyrSkg6OcHfnI
wTSKn9ZkixjYUehcSCVGC2ED06HElEeHsfxVyZKOc52c+h0d0dpy8h92GowrLUTK
fa7w67Jx+YG9R/A5WHkyqKHbuMIb2rEJXnUVl3wf6RNKDfdR8cX8N4K4+7MS4Szx
ZuyQqBUqfng+PLHkujuZE5fXWkbmhjt3X1yE8DHDTQszttSKhAHK5mQxkN/Ja1UX
FkNbmqqZlKdrq1Qdp/N7vKJ4+23ePQxr3ml0Y6uCcQKBgQDdw3PrNmHgN0R+AKAy
OudFoYAjAISvraksSPkzVhwr74MI6sQcb2qKjImrTzLzDV1kNx04pc6kGlJXMDS+
miBK+b3GIb/u4DVqS04wHI3a58nehG3QjHsht+Bywn3Irg6YrjP8e0oaBY0t1M8d
jRUPg2gbZw8WSeT1MijY+lmehwKBgQDa5jDQ/AC42EDlPklszNfYrzz2Ko2e9JCC
m7S2rIaJEWRnGJAslQdgGVgXVGy37jf7BInfrMwZBfh36atL8Zi0snD+q9uSainm
dnkIg4FfL4ylc/Lmp6AC+Gf4tTfgEjt48vjeOfmSk0LO7rLQtlvYiiXAb3b06g9c
ioLw4dWpxQKBgGolaLG4GQciTRVmpUcFrLdGgze9wsT4AZah4y3wVJGvFfBJts7J
gZyJgkfOI9v0lLQoMUNxEcS4mJsFBuoIidZ5TZ2tf9oN1WNoYidjM38JHTX1+z4s
T6+m/LbRYzWQIopwL4/1T1W/PIEocG57ng4L3uPm43DOs9mtRaH9yrG3AoGAfYHO
K4TRxSn4y3fTEZbBi3OuOFZdrO38jWZJTxPMb3qRXqsuvuETwX3GjFnTnAHyBvKr
OpwQyagqtlY76Oc07yYAs4RF+MT2ETWMX91GqBTTR2obszQZApr6whblWowZnVdy
abhD6E6W157018Y3EwjibFt8kSBCfoTMXuCdaSECgYBlPfryWixx9VcgUbuayWLJ
CrNso6XctztvDrlBqcAA3cAwJQCIEX8EE7MAwymFgpX3KKDmp1SC2Cv6MNEQ6FAH
IL42CDQbxqQ0DnrmjcZf/qaF1jCE8clqazsZ7w6a7QXWe2xtW3HPnatNU6X0EVFe
m1bgIzfBojLVOevA0gZBBg==
-----END PRIVATE KEY-----
"""
client_email = "fast-campus@braided-complex-481413-h8.iam.gserviceaccount.com"
client_id = "115244630889267827857"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/fast-campus%40braided-complex-481413-h8.iam.gserviceaccount.com"
